config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"

  resources :events, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!
  
  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    redirect_to event_path(@event)
  end

  def index
    @events = Event.all.order('created_at DESC').page(params[:page]).per(params[:per_page] || 10)
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:image)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h3 class="text-center">Events</h3>

<div class="row">

  <% @events.each do |e| %>
    <%= link_to event_path(e), :class=>"event_link" do %>
      <div class="col-sm-4 col-xs-6 event_thumb">
        <%= image_tag e.image.url(:medium) %></br>
        <%= e.image_file_name %></br>
        <%= e.created_at.localtime.strftime("%a, %d %b %Y %I:%M:%S %p") %>
      </div>
    <% end %>
  <% end %>

</div>

<div class="footer">
  <%= paginate @events %>
</div>

app/views/events/new.html.erb
<h3 class="text-center">New Event</h3>


<%= form_for @event, url: events_path, html: { multipart: true } do |f| %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit %>

<% end %>

app/views/events/show.html.erb
<h3 class="text-center"><%= @event.image_file_name %></h3>
<%= link_to "Return to Events Index", events_path %></br>
<div class="col-xs-12 event_thumb">
  <%= image_tag @event.image.url %></br>
  <%= @event.created_at.localtime.strftime("%a, %d %b %Y %I:%M:%S %p") %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Necro-Cam</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Livestream <span class="sr-only">(current)</span></a></li>
        <li><a href="/events">Events</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/users/edit">Edit Profile</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Sign Out</a></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/users/sign_in">Sign in</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NecroCam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice %>
      <p class="notice"><%= notice %></p> 
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>    
  </body>
</html>

app/views/welcome/index.html.erb
<h3 class="text-center">Livestream</h5>

<p class="text-center">68.3.186.5</p>
<img src="http://68.3.186.5:666/" class="img-responsive" alt="If you are unable to see the external live stream please try again using the Firefox browser or contact us."></img>

<p class="text-center">192.168.1.183</p>
<div class="col-xs-12">
  <img src="http://192.168.1.193:8081/" class="img-responsive" alt="If you are unable to see the internal live stream please try again using the Firefox browser or contact us."></img>
</div>